#define SYS_BeginFrameDraw  0
#define SYS_EndFrameDraw    1
#define SYS_WaitFrame       2
#define SYS_Blit            3
#define SYS_BlitRam         4
#define SYS_BlitChar        5
#define SYS_BlitStr         6
#define SYS_BlitStrRam      7
#define SYS_GetKey          8
#define SYS_GetMouseButtons 9
#define SYS_GetMouseX       10
#define SYS_GetMouseY       11
